
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dsml
    username: root
    password: zhrsql

# mvc配置
  mvc:
    view:
      suffix: .html
      static-path-pattern: /**
      resources:
          static-locations: classpath:/static/

  #引擎模板配置
  thymeleaf:
    mode: HTML
    cache: false

server:
  port: 8080
  servlet:
    context-path: /dsml