
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dsml?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhrsql

  #引擎模板配置
  thymeleaf:
    mode: HTML
    cache: false

server:
  port: 8080
  servlet:
    context-path: /dsml
#项目存放位置
dsml:
   path: D:/dsml/